### ISSUE TITLE
не собирается проект, отсутствует пакет xmlobjects

### ISSUE THREAD

**Issue by Sysor** [lalexs75/scancode_fpc#1]

**Comment by lalexs75** [comment]
Необходимо дополнительно установить пакет protobuf-fpc - тут находится ядро сериализации паскаль объектов в xml.
https://github.com/lalexs75/protobuf-fpc

ЗЫ
Сам компонент ещё не доделан. Интерфейс не стабилен - может что то буду переиписывать. Как добью весь требуемый мне функционал - тогда на форумах объявлю.
